open-feature/java-sdk

LICENSE
=> Add Apache2.0 license

lib/src/main/java/dev/openfeature/javasdk/EvaluationContext.java, lib/src/main/java/dev/openfeature/javasdk/Hook.java, lib/src/main/java/dev/openfeature/javasdk/HookContext.java, lib/src/main/java/dev/openfeature/javasdk/OpenFeatureClient.java, lib/src/test/java/dev/openfeature/javasdk/DeveloperExperienceTest.java, lib/src/test/java/dev/openfeature/javasdk/EvalContextTests.java, lib/src/test/java/dev/openfeature/javasdk/FlagEvaluationSpecTests.java, lib/src/test/java/dev/openfeature/javasdk/HookSpecTests.java
Blocked waiting on EvalContext spec to be finalized.
=> Evaluation Context support

.gitignore, lib/src/main/java/dev/openfeature/javasdk/BaseEvaluation.java, lib/src/main/java/dev/openfeature/javasdk/Client.java, lib/src/main/java/dev/openfeature/javasdk/FeatureProvider.java, lib/src/main/java/dev/openfeature/javasdk/FlagEvaluationDetails.java, lib/src/main/java/dev/openfeature/javasdk/HookContext.java, lib/src/main/java/dev/openfeature/javasdk/Metadata.java, lib/src/main/java/dev/openfeature/javasdk/NoOpProvider.java, lib/src/main/java/dev/openfeature/javasdk/OpenFeatureAPI.java, lib/src/main/java/dev/openfeature/javasdk/OpenFeatureClient.java, lib/src/main/java/dev/openfeature/javasdk/ProviderEvaluation.java, lib/src/test/java/dev/openfeature/javasdk/AlwaysBrokenProvider.java, lib/src/test/java/dev/openfeature/javasdk/DeveloperExperienceTest.java, lib/src/test/java/dev/openfeature/javasdk/DoSomethingProvider.java, lib/src/test/java/dev/openfeature/javasdk/EvalContextTests.java, lib/src/test/java/dev/openfeature/javasdk/FlagEvaluationSpecTests.java, lib/src/test/java/dev/openfeature/javasdk/HookContextTest.java, lib/src/test/java/dev/openfeature/javasdk/HookSpecTests.java, lib/src/test/java/dev/openfeature/javasdk/MetadataTest.java, lib/src/test/java/dev/openfeature/javasdk/NotImplementedException.java, lib/src/test/java/dev/openfeature/javasdk/ProviderSpecTests.java, lib/src/test/java/dev/openfeature/javasdk/Specification.java, spec_finder.py
Made a tool to validate if we're current w/ the spec, then fixed all the tests so that we are.
=> Update with latest spec

src/main/java/dev/openfeature/javasdk/EvaluationContext.java, src/main/java/dev/openfeature/javasdk/FeatureProvider.java, src/main/java/dev/openfeature/javasdk/NoOpProvider.java, src/test/java/dev/openfeature/javasdk/AlwaysBrokenProvider.java, src/test/java/dev/openfeature/javasdk/DoSomethingProvider.java, src/test/java/dev/openfeature/javasdk/EvalContextTest.java, src/test/java/dev/openfeature/javasdk/HookSpecTest.java, src/test/java/dev/openfeature/javasdk/NoOpProviderTest.java, src/test/java/dev/openfeature/javasdk/ProviderSpecTest.java
Signed-off-by: Robert Grassian <robert.grassian@split.io>
=> iterators to get all integer, string, boolean, or structure map entries

src/main/java/dev/openfeature/javasdk/DoubleHook.java, src/test/java/dev/openfeature/javasdk/fixtures/HookFixtures.java
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> add double hook interface

README.md, release-please-config.json
Release Please will now bump the version on the readme as part of the release PR.
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> chore: update release please to manage versions on the readme

.github/dependabot.yml
Fixes dependabot PR titles to be semantic.
=> chore: fix dependabot pr titles

pom.xml
=> feat: Support for generating CycloneDX sboms

.github/workflows/pullrequest.yml
Signed-off-by: Justin Abrahms <jabrahms@ebay.com>
=> chore: I don't think we use that permission?

.github/workflows/pullrequest.yml, pom.xml, src/test/java/dev/openfeature/sdk/integration/StepDefinitions.java
Update test harness and re-enable integration test profile
closes: https://github.com/open-feature/java-sdk/issues/113
=> chore: re-enable integration tests

.github/workflows/cflite_batch.yml
Failing run: https://github.com/open-feature/java-sdk/actions/runs/3551397639/jobs/5965541188
=> chore: The language is jvm, not java.

renovate.json
- Addresses the Renovate bot configuration issues
Fixes #201
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> chore: update renovate bot configuration

pom.xml, src/test/java/dev/openfeature/sdk/integration/StepDefinitions.java
Absorbs breaking updates to cuke tests.
=> chore: update cuke submodule, tests

src/main/java/dev/openfeature/sdk/Reason.java
As per: https://github.com/open-feature/spec/blob/7ed7442c40d4e766424671258846b21a96adda70/specification/types.md#resolution-details
Signed-off-by: Todd Baert <toddbaert@gmail.com>
=> feat: add STATIC, CACHED reasons

release-please-config.json
- Extends the changelog with more sections... and emojis!
=> chore: add changelog sections

.github/workflows/merge.yml, .github/workflows/pullrequest.yml, renovate.json
see: https://github.com/codecov/codecov-action/issues/1087
=> chore: disable action pinning, revert codecov

.github/workflows/release.yml, release-please-config.json
Attempt to fix RP workflow after updating to v4
=> chore: attempt to fix rp workflow

README.md
- Fix typo in https://openfeature.dev/docs/reference/technologies/server/java#usage
- Align indent
https://github.com/open-feature/openfeature.dev/pull/323 was original PR
=> chore: fix typo and indent in tutorial

benchmark.txt, src/test/java/dev/openfeature/sdk/benchmark/AllocationBenchmark.java
This just improves the quality of the benchmark by adding more contexts, which allows us to see the impact of merging more clearly.
=> chore: improve benchmark realism; add more context

.github/workflows/release.yml, release-please-config.json
Adding signoff to release plz PRs.
=> chore: add DCO to release please

.github/workflows/release.yml
=> chore: update release please action

.github/workflows/merge.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml
=> chore: fix checkout
