open-feature/java-sdk

- lib/build.gradle
- lib/src/test/java/dev/openfeature/javasdk/FlagEvaluationSpecTests.java
This PR addresses #16 and can be used as a blueprint for other tests asserting log messages.
-removes dependency to log4j binding for slf4j, so clients can choose a different binding
-adds dependency to slf4j-api
-adds test logging binding by adding (test) dependency to uk.org.lidalia:slf4j-test
-adds (test) dependency to assertj for better readable assertions
> [16] Tests for logging to validate 1.4.10 (#1)

- src/main/java/dev/openfeature/javasdk/EvaluationContext.java
The `EvaluationContext` constructor is not public.
I tried this simple class on my side and was not able to use the `EvaluationContext`
```java
package org.gofeatureflag;
import dev.openfeature.javasdk.EvaluationContext;
import dev.openfeature.javasdk.NoOpProvider;
import dev.openfeature.javasdk.OpenFeatureAPI;
public class Main {
public static void main(String[] args) {
OpenFeatureAPI api = OpenFeatureAPI.getInstance();
api.setProvider(new NoOpProvider());
var client = api.getClient();
var ctx = new EvaluationContext();
ctx.setTargetingKey("uniqID");
client.getBooleanValue("test-flag", Boolean.FALSE, ctx);
}
}
```
For information, the error I receive is:
```
'EvaluationContext()' is not public in 'dev.openfeature.javasdk.EvaluationContext'. Cannot be accessed from outside package
``` …
> fix: EvaluationContext make constructor public

- .github/workflows/pullrequest.yml
This PR ensures that we are signing the jar in our pull request only if it is not a fork repo.
> ignore GPG Key for fork repos

- src/main/java/dev/openfeature/javasdk/FeatureProvider.java
- src/main/java/dev/openfeature/javasdk/NoOpProvider.java
- src/test/java/dev/openfeature/javasdk/AlwaysBrokenProvider.java
- src/test/java/dev/openfeature/javasdk/DoSomethingProvider.java
- src/test/java/dev/openfeature/javasdk/NoOpProviderTest.java
- src/test/java/dev/openfeature/javasdk/ProviderSpecTest.java
This PR adds the support of `double` value from the flags.
Resolves #32
> feat: Add method to get double

- src/main/java/dev/openfeature/javasdk/EvaluationContext.java
- src/test/java/dev/openfeature/javasdk/EvalContextTest.java
The evaluation context sets the targeting key to `""` by default in the constructor. Therefore when two contexts are merged the targeting key is never null and these checks are always true. This results in setting the targeting key always to `""` if `ctx2` did not have a targeting key set, regardless if `ctx1` does have it set
> fix merge of eval context targeting key

- .gitignore
- src/main/java/dev/openfeature/javasdk/HookSupport.java
- src/main/java/dev/openfeature/javasdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/javasdk/DeveloperExperienceTest.java
- src/test/java/dev/openfeature/javasdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/javasdk/ProviderSpecTest.java
- Falls back to the no-op provider if not set. This is an easy way to assure there's no errors thrown if a user has forgotten to register a provider, or due to an race condition where a flag is evaluated before a provider is registered. This is consistent with what's done in the [dotnetSDK](https://github.com/open-feature/dotnet-sdk/blob/73fd72e7190eea585ccefb1116ed778dc2cc740b/src/OpenFeature.SDK/OpenFeature.cs#L15) and the [Node.JS SDK](https://github.com/open-feature/node-sdk/blob/5051681699fd5d805bb8a3ddccd692c45ac95f9e/src/open-feature.ts#L14)
- Moves all author code into the try/catch in the evaluation logic, meaning that we should always get a default, even if authors throw in `provider.getMetadata` or something silly like that
> fix: Set no-op provider by default, handle null providers

- src/main/java/dev/openfeature/javasdk/FeatureProvider.java
- src/main/java/dev/openfeature/javasdk/NoOpProvider.java
- src/main/java/dev/openfeature/javasdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/javasdk/AlwaysBrokenProvider.java
- src/test/java/dev/openfeature/javasdk/DoSomethingProvider.java
I neglected to change T -> Structure in the `FeatureProvider` interface (I only got the `Features` interface which corresponds to the evaluation API) in https://github.com/open-feature/java-sdk/pull/51. T is so permissive, that it was easy to miss since there wasn't compilation errors.
We certainly want the type in the provider to match the evaluation API.
Since this just changes generics, I believe there is no runtime changes here.
> fix: update provider object eval, T -> Structure

- .github/workflows/release.yml
- README.md
- pom.xml
An expression in the `version` attr (e.g. `<version>0.1.0${version.modifier}</version>`) is causing [issues](https://github.com/open-feature/java-sdk/issues/56#issuecomment-1236223635) for gradle.
Instead of using expressions in the pom, this PR modifies the release action to use `mvn versions:set -DremoveSnapshot` to remove the `-SNAPSHOT` modifier, which is built-in functionality of the maven version plugin.
I think long term, we want to move to [release please](https://github.com/googleapis/release-please) for a few reasons:
- it uses [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to keep track of when we should consider versions breaking
- it can be configured to update all instances of a version, across all files in the repo (so even our readme will be updated …
> use mvn version to remove -SNAPSHOT, bump 0.1.1

- src/main/java/dev/openfeature/javasdk/Structure.java
- src/main/java/dev/openfeature/javasdk/Value.java
- src/test/java/dev/openfeature/javasdk/StructureTest.java
- src/test/java/dev/openfeature/javasdk/ValueTest.java
- As per https://github.com/open-feature/java-sdk/issues/58, `Value` now stores all numbers as doubles. `Value.isDouble()`/`Value.isInteger()` consolidated to `Value.isNumber()`. `Value.asInteger()` now returns the rounded inner double using `Math.round()`.
Also includes a few non-breaking changes:
- new `add` overload for adding Value type to struct: `Structure.add(String key, Value value)`
- new `Value()` constructor to construct a null Value.
- specific testing for Structure/Value.
Closes: https://github.com/open-feature/java-sdk/issues/58
> breaking: store all numbers as doubles

- src/main/java/dev/openfeature/javasdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/javasdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/javasdk/FlagEvaluationSpecTest.java
BREAKING: We had `setCtx()` on the global API and `setEvaluationContext()` on the client. This PR makes them both:  `setEvaluationContext()`
We don't have to do this, but since we already have breaking changes for the next release, I think it makes sense. Let me know if the previous was was intentional.
> !feat: Make evaluation accessors setters consistent

- src/main/java/dev/openfeature/javasdk/EvaluationContext.java
- src/main/java/dev/openfeature/javasdk/FeatureProvider.java
- src/main/java/dev/openfeature/javasdk/Features.java
- src/main/java/dev/openfeature/javasdk/NoOpProvider.java
- src/main/java/dev/openfeature/javasdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/javasdk/Structure.java
- src/main/java/dev/openfeature/javasdk/Value.java
- src/test/java/dev/openfeature/javasdk/AlwaysBrokenProvider.java
- src/test/java/dev/openfeature/javasdk/DoSomethingProvider.java
- src/test/java/dev/openfeature/javasdk/EvalContextTest.java
- src/test/java/dev/openfeature/javasdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/javasdk/NoOpProviderTest.java
- src/test/java/dev/openfeature/javasdk/ProviderSpecTest.java
- src/test/java/dev/openfeature/javasdk/StructureTest.java
- src/test/java/dev/openfeature/javasdk/ValueTest.java
This is a collection of small (but breaking) changes. I hope these are the last breaking changes before a 1.0rc. I've broken it into 3 commits for easy understanding:
- add object constructor and accessor to `Value`: https://github.com/open-feature/java-sdk/commit/0152a1eef93ea1b5253ddae78718a9805c98aaf7
- use `Instant` instead of `ZonedDateTime` (https://github.com/open-feature/java-sdk/issues/59): https://github.com/open-feature/java-sdk/commit/3e6241422266825f267043e4acd116803c4939b0
- use `Value` instead of `Structure` in object resolver (https://github.com/open-feature/spec/issues/138#issuecomment-1241202093): https://github.com/open-feature/java-sdk/commit/5d262470e8ec47d2af35f0aabe55e8c969e992ac
> Collection of small, breaking changes

- src/main/java/dev/openfeature/javasdk/Structure.java
- src/main/java/dev/openfeature/javasdk/exceptions/ValueNotConvertableError.java
- src/test/java/dev/openfeature/javasdk/EvalContextTest.java
Add a new method called `asObjectMap` that convert the `EvaluationContext` into a `Map<String,Object>`.
This utility method will be used by the providers when they have to convert the `EvaluationContext` to transform them into the query they need to send to the backend system.
> feat: Add asObjectMap to get the EvaluationContext as Map<String,Object>

- pom.xml
- spotbugs-exclusions.xml
- src/main/java/dev/openfeature/sdk/Client.java
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/internal/AutoCloseableLock.java
- src/main/java/dev/openfeature/sdk/internal/AutoCloseableReentrantReadWriteLock.java
- src/test/java/dev/openfeature/sdk/DeveloperExperienceTest.java
- src/test/java/dev/openfeature/sdk/DoSomethingProvider.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/sdk/LockingTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureClientTest.java
This PR adds multi-read/single-write locks to both the global singleton and the client. Particularly it addresses problems relating to the providers/hooks being mutated while an evaluation is occurring. This is especially important since some providers have provider hooks, and if we dont lock, it's possible hooks from proivder1 run on provider2 if an interleaving thread switched the provider.
To make things cleaner and less error-prone, I've created a little wrapper so we can use `try-with-resources` blocks.
This way, locking can be done like:
```
public void addHooks(Hook... hooks) {
try (AutoCloseableLock __ = rwLock.writeLockAutoCloseable()) {
this.apiHooks.addAll(Arrays.asList(hooks));
}
}
```
...with no need to explicitly close the lock.
I'm going to write some tests in the morning …
> fix!: add rw locks to client/api, hook accessor name

- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/sdk/OpenFeatureClientTest.java
Signed-off-by: Robert Grassian <robert.grassian@split.io>
- Fixes merging of eval contexts. Client eval context was ignored due to a bug.
Fixes #1234523
Added a new test for this in `OpenFeatureClientTest`. It passes with my fix and fails without it.
> fix: merge eval context

- README.md
- checkstyle-suppressions.xml
- checkstyle.xml
- pom.xml
- spotbugs-exclusions.xml
- src/main/java/dev/openfeature/sdk/BooleanHook.java
- src/main/java/dev/openfeature/sdk/DoubleHook.java
- src/main/java/dev/openfeature/sdk/ErrorCode.java
- src/main/java/dev/openfeature/sdk/FlagEvaluationDetails.java
- src/main/java/dev/openfeature/sdk/FlagEvaluationOptions.java
- src/main/java/dev/openfeature/sdk/FlagValueType.java
- src/main/java/dev/openfeature/sdk/HookSupport.java
- src/main/java/dev/openfeature/sdk/IntegerHook.java
- src/main/java/dev/openfeature/sdk/MutableStructure.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/ProviderEvaluation.java
- src/main/java/dev/openfeature/sdk/Reason.java
- src/main/java/dev/openfeature/sdk/StringHook.java
- src/main/java/dev/openfeature/sdk/Value.java
- src/main/java/dev/openfeature/sdk/exceptions/FlagNotFoundError.java
- src/main/java/dev/openfeature/sdk/exceptions/GeneralError.java
- src/main/java/dev/openfeature/sdk/exceptions/InvalidContextError.java
- src/main/java/dev/openfeature/sdk/exceptions/OpenFeatureError.java
- src/main/java/dev/openfeature/sdk/exceptions/ParseError.java
- src/main/java/dev/openfeature/sdk/exceptions/TargetingKeyMissingError.java
- src/main/java/dev/openfeature/sdk/exceptions/TypeMismatchError.java
- src/main/java/dev/openfeature/sdk/exceptions/ValueNotConvertableError.java
- src/main/java/dev/openfeature/sdk/internal/AutoCloseableLock.java
- src/main/java/dev/openfeature/sdk/internal/ObjectUtils.java
This just fixes an issue that prevents JDK 11+ from working with our build and adds some associated missing javadoc. This is troublesome if you happen to be working with other projects that require a later version of the JDK.
Specifically, there were changes in later versions of `javac` that applied more rules, mostly around javadoc. These caused errors we could not customize, so I've disabled the lint checks in the `maven-javadoc-plugin` and I instead enforce them with `checkstyle`, which is more customizable.
> chore: fix issues with compilation on later JDKs

- renovate.json
I believe this will auto-merge action updates on successful CI (see: https://docs.renovatebot.com/modules/manager/github-actions/#default-config)
The risk here is that it breaks an action (or action paths) not used in the PR CI, but I _think_ it's worth it?
> chore: automerge action updates

- README.md
- renovate.json
Add renovate config to monitor test-harness version and upgrade flagd-testbed image.
Fixes #237
> chore: renovate regex manager to monitor test-harness version

- src/main/java/dev/openfeature/sdk/EvaluationContext.java
- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/ImmutableStructure.java
- src/main/java/dev/openfeature/sdk/MutableStructure.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/Structure.java
- src/main/java/dev/openfeature/sdk/Value.java
- src/test/java/dev/openfeature/sdk/DeveloperExperienceTest.java
- src/test/java/dev/openfeature/sdk/EvalContextTest.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/sdk/HookContextTest.java
- src/test/java/dev/openfeature/sdk/HookSpecTest.java
- src/test/java/dev/openfeature/sdk/HookSupportTest.java
- src/test/java/dev/openfeature/sdk/ImmutableContextTest.java
- src/test/java/dev/openfeature/sdk/ImmutableStructureTest.java
- src/test/java/dev/openfeature/sdk/LockingTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureClientTest.java
- src/test/java/dev/openfeature/sdk/ProviderSpecTest.java
- src/test/java/dev/openfeature/sdk/integration/StepDefinitions.java
Signed-off-by: thiyagu06 <thiyagu103@gmail.com>
added implementation of immutable evaluation context
Fixes #161
> feat:  added implementation of immutable evaluation context

- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
Fixes #275
Consider the following log entry with detailed logs explaining the underlying issue by logging stacktrace,
> fix: improve error logs for evaluation failure

- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/main/java/dev/openfeature/sdk/Structure.java
- src/test/java/dev/openfeature/sdk/ImmutableContextTest.java
Signed-off-by: Javier Collado <javicv@gmail.com>
- Makes the evaluation context merge recursive for both MutableContext and ImmutableContext
Fixes #270
- A new test method _mergeShouldRetainItsSubkeysWhenOverridingContextHasTheSameKey_ in _dev.openfeature.sdk.ImmutableContextTest_ has been added
> fix: MutableContext and ImmutableContext merge are made recursive

- src/main/java/dev/openfeature/sdk/EvaluationContext.java
- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/test/java/dev/openfeature/sdk/EvalContextTest.java
- src/test/java/dev/openfeature/sdk/ImmutableContextTest.java
Signed-off-by: thiyagu06 <thiyagu103@gmail.com>
remove the deprecated setTargetingKey method in EvaluationContext.
https://github.com/open-feature/java-sdk/issues/253
> feat: remove the deprecated setTargetingKey method in EvaluationContext.

- src/main/java/dev/openfeature/sdk/ImmutableStructure.java
- src/test/java/dev/openfeature/sdk/ImmutableStructureTest.java
I noticed when implementing a provider that accessing a missing item from an ImmutableContext throws an exception instead of returning null. I do not believe this to be the desired behavior.
I think the added unit test should cover it.
> fix: Do not throw null reference exception accessing a missing item.

- src/main/java/dev/openfeature/sdk/Structure.java
- src/main/java/dev/openfeature/sdk/Value.java
- src/test/java/dev/openfeature/sdk/ValueTest.java
- stores Number instead of Double
- removes custom conversion from double to int and relies instead on API that respects Java Specs https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.1.3
This is a proposal
> fix: handling of double and integer

- src/main/java/dev/openfeature/sdk/Value.java
- src/test/java/dev/openfeature/sdk/ValueTest.java
Fixes #286
`Value.isList()` now validate list internal objects to be `Value` typed
> fix: validate list content to be values

- pom.xml
- Adds an automatic module name that is more descriptive than `sdk`.  The new module name is `dev.openfeature.sdk`.
Fixes #362  
This is the easy fix, modularizing the entire Jar would take longer.  There might be a better way to achieve this but I am not a maven expert.
After the change the produced Jar should have `Automatic-Module-Name: dev.openfeature.sdk` in the `META-INF/MANIFEST.MF` file.
> fix: added an automatic module name (#362)

- CONTRIBUTING.md
- README.md
Updates the README for consistency, see [here](https://github.com/open-feature/.github/pull/36).
Direct preview: https://github.com/open-feature/java-sdk/blob/187b1135eb84dd83c6948c29bbb8e1f4448cc5fe/README.md
> chore: update readme using template

- .github/workflows/pullrequest.yml
- CONTRIBUTING.md
- pom.xml
- src/test/java/dev/openfeature/sdk/e2e/RunCucumberTest.java
- src/test/java/dev/openfeature/sdk/e2e/StepDefinitions.java
As has been brought up a few times, "end-to-end" is probably a better term for these tests, since they startup multiple processes and do inter-process communication streams with real (not mocked) artifacts.
No functional changes. I did use git mv to try to preserve history as best as possible.
> chore: rename integration tests e2e

- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/sdk/ClientProviderMappingTest.java
- src/test/java/dev/openfeature/sdk/DeveloperExperienceTest.java
- src/test/java/dev/openfeature/sdk/EvalContextTest.java
- src/test/java/dev/openfeature/sdk/ImmutableStructureTest.java
- src/test/java/dev/openfeature/sdk/LockingTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureAPITest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureClientTest.java
This adds support for mapping a client name onto a given provider, while still providing backwards compatibility to existing clients.
Refs https://github.com/open-feature/ofep/pull/56
Fixes: https://github.com/open-feature/java-sdk/issues/442
I still need to clean up documentation around this to note the difference between a "default provider" and a client-specific provider.
Not sure about testing, but I'd especially love eyes on the thread safety. I don't think ConcurrentHashMap is doing a lot of work here, given we have to use locks to support `getProviderForClientOrDefault`. If you have a better way, I'm all ears.
> feat: Support mapping a client to a given provider.

- src/main/java/dev/openfeature/sdk/FlagEvaluationDetails.java
- src/main/java/dev/openfeature/sdk/FlagMetadata.java
- src/main/java/dev/openfeature/sdk/ProviderEvaluation.java
- src/test/java/dev/openfeature/sdk/DoSomethingProvider.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/sdk/FlagMetadataTest.java
Is connected to #437 & completes the implementation of flag metadata spec implementation [1]
The implementation is backed by immutable `FlagMetadata`. If present, metadata gets propagated from `ProviderEvaluation` to `FlagEvaluationDetails`
Tests were added to validate the construction as well as the propagation 
[1] - https://github.com/open-feature/spec/commit/74c373e089ad77bf8cac84f3d93c00c945ff3a8a
> feat: add flag metadata

- .github/workflows/merge.yml
Setting a Codecov token helps avoid throttling issues.
> ci: add codecov token

- src/main/java/dev/openfeature/sdk/FlagMetadata.java
- src/test/java/dev/openfeature/sdk/FlagMetadataTest.java
Make the `getValue` method public for `FlagMetadata.java`. This allows generic value extractions where needed (ex:- Loop across <key, type> and extract them from flag metadata instead of checking for type and calling the exact method).
```
for (DimensionDescription description:dimensionDescriptions) {
flagMetadata.getValue(description.getKey(), description.getType());
}
// where 
DimensionDescription is <key of String, type of Class>
```
> chore: expose get value for metadata

- pom.xml
Attempts to improve local development experience by isolating artifact release time plugins into a dedicated profile. Profile `deploy` is activated by default, hence no change is needed in CI (GH Actions). However, the developer now can disable this profile with profile disable command `<mvn command> -P -deploy` so that they do not need to worry about deploy time executions (ex:- artifact signing)
For local development builds without release, signing and java docs use maven command -  `mvn clean install -P -deploy`
> chore: seperate release plugins to a profile

- src/main/java/dev/openfeature/sdk/FlagEvaluationDetails.java
- src/main/java/dev/openfeature/sdk/ImmutableMetadata.java
- src/main/java/dev/openfeature/sdk/ProviderEvaluation.java
- src/test/java/dev/openfeature/sdk/DoSomethingProvider.java
- src/test/java/dev/openfeature/sdk/FlagMetadataTest.java
Renames the `FlagMetadata` class (it can be used for event metadata as well). Talked with @Kavindu-Dodan (the implementer) about this. This is not yet released, so there's no breaking change to worry about.
> chore: rename flag metadata

- README.md
- improves the copy used on the readme
- updates provider and hook links to use the ecosystem page
Update the org-level readme template if the copy changes are approved.
> chore: update copy and links on the readme

- README.md
> chore: update readme for events

- src/main/java/dev/openfeature/sdk/ImmutableMetadata.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationDetailsTest.java
- Implement the `equals` method to be able to compare 2 `FlagEvaluationDetails`.
Fixes #511
> fix:  Implement equals for the ImmutableMetadata object

- .github/workflows/pullrequest.yml
- CONTRIBUTING.md
- pom.xml
Adds some TODOs related to https://github.com/open-feature/java-sdk/issues/523.
Also pulls a _specific_ submodule instead of all of them via recursive, since this can cause failures when multiple jobs pull submodules at the same time.
> chore: add todos, fix submodule pull

- src/main/java/dev/openfeature/sdk/EventSupport.java
I believe this was causing intermittent failures with tests. This static field on a package private member meant that the instance we created for testing (which we shutdown) was shared with the "real" API instance (see [here](https://github.com/open-feature/java-sdk/actions/runs/5765050607/job/15630249339#step:7:753) for an example failure).
I don't think this constitutes a production bug, but it should make our tests more reliable.
Edit: I ran this suite locally 10+ times and in GH 5 times and it seems to run reliably now.
> chore: fix race with events tests

- src/main/java/dev/openfeature/sdk/EventProvider.java
- src/main/java/dev/openfeature/sdk/FeatureProvider.java
- src/test/java/dev/openfeature/sdk/EventProviderTest.java
In 3 event provider implementations, [flagd-java](https://github.com/open-feature/java-sdk-contrib/pull/361#pullrequestreview-1541468446), [go-feature-flag-web](https://github.com/open-feature/js-sdk-contrib/pull/474#discussion_r1274012627), and even my own implementation of flagd-js, authors have forgotten to properly implement `getState` (which means the SDK assumes the provider is already `READY` and doesn't run `initialize()`.)
This is an easy pitfall. To help with this, I'm making the implementation of `getState` required in the abstract `EventProvider` class, and will do similarly in the JS-SDK. I think this is a reasonable proposal because the `EventProvider` class is very new, and in the majority of cases a provider that can fire async events requires some kind of remote …
> fix: getState mandatory on EventProvider

- src/main/java/dev/openfeature/sdk/EventSupport.java
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/test/java/dev/openfeature/sdk/ShutdownBehaviorSpecTest.java
Fix #552 
Since API is a singleton, we must re-initialize all cleaned-up resources.
> fix: ability to set provider after shutdown

- src/main/java/dev/openfeature/sdk/exceptions/ProviderNotReadyError.java
- src/main/java/dev/openfeature/sdk/providers/memory/InMemoryProvider.java
- src/test/java/dev/openfeature/sdk/e2e/StepDefinitions.java
- src/test/java/dev/openfeature/sdk/providers/memory/InMemoryProviderTest.java
Small changes to satisfy jacoco coverage failing in main (bring above 80%).
Also throwing in the new in-memory provider instead of returning error resolutions.
cc @liran2000 I missed these small things on your PR. I hope they make sense.
> chore: fix jacoco coverage minimum, throw in memory provider

- README.md
Updating README to conform to auto-inclusion for openfeature.dev
> docs: update README to be auto-included in openfeature.dev

- src/main/java/dev/openfeature/sdk/ProviderRepository.java
fix NPE on named provider initialization.
When initializing named provider first time, NPE is thrown.  
This may cause old provider to not shutdown properly.
Add null check on _isProviderRegistered_.
1. Add dependency at pom.xml to see logs on console:
```
<dependency>
<groupId>org.apache.logging.log4j</groupId>
<artifactId>log4j-slf4j2-impl</artifactId>
<version>2.20.0</version>
<scope>test</scope>
</dependency>
```
2. Run relevant individual unit test, e.g. _dev.openfeature.sdk.EventsTest.ApiEvents.NamedProvider.Initialization_.
3. Observe console log. Without this fix, the following error appears:
```
java.lang.NullPointerException: null
at java.util.concurrent.ConcurrentHashMap.containsValue(ConcurrentHashMap.java:979) ~[?:?]
at …
```
> fix: NPE on named provider init/shutdown

- src/main/java/dev/openfeature/sdk/EventSupport.java
- src/main/java/dev/openfeature/sdk/ProviderRepository.java
Fixes https://github.com/open-feature/java-sdk/issues/600
Makes task executor threads daemons.
> fix: make executor threads deamon

- README.md
- Updated the `setProviderAndWait` example in the quick start section
- Expand the provider's section to show both the async and synchronous options.
Update readme examples to include `setProviderAndWait`
Fixes #592 
If there are any corrections, please let me know.
> docs: document setProviderAndWait in README

- src/main/java/dev/openfeature/sdk/ProviderRepository.java
- src/test/java/dev/openfeature/sdk/ProviderRepositoryTest.java
- don't reset noop provider on `ProviderRepository` shutdown, not necessary anyway since we create a whole new `ProviderRepository` on shutdown
- updated related tests
@Kavindu-Dodan you were exactly right on the cause.
Fixes: https://github.com/open-feature/java-sdk/issues/647
> fix: RejectedExecutionException on shutdown

- README.md
- src/main/java/dev/openfeature/sdk/EventDetails.java
- src/main/java/dev/openfeature/sdk/FlagEvaluationDetails.java
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/sdk/ProviderState.java
- src/test/java/dev/openfeature/sdk/DoSomethingProvider.java
- src/test/java/dev/openfeature/sdk/EventsTest.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/sdk/HookContextTest.java
- src/test/java/dev/openfeature/sdk/HookSpecTest.java
- src/test/java/dev/openfeature/sdk/InitializeBehaviorSpecTest.java
- src/test/java/dev/openfeature/sdk/LockingTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureAPITest.java
- src/test/java/dev/openfeature/sdk/ProviderSpecTest.java
- src/test/java/dev/openfeature/sdk/ShutdownBehaviorSpecTest.java
- src/test/java/dev/openfeature/sdk/testutils/TestEventsProvider.java
* run any event handler immediately if the provider is in the associated state, not just ready
* add providerName to event details
* add STALE provider state
* update/add associated tests
* also fixed spec/test associations mismatches from previous changes
fixes: https://github.com/open-feature/java-sdk/issues/599
> feat: implement spec 0.7.0 changes

- .github/workflows/release.yml
> chore: releases to release

- checkstyle.xml
- src/main/java/dev/openfeature/sdk/EventProvider.java
- src/main/java/dev/openfeature/sdk/ProviderRepository.java
- src/test/java/dev/openfeature/sdk/OpenFeatureAPITest.java
- src/test/java/dev/openfeature/sdk/ProviderRepositoryTest.java
- src/test/java/dev/openfeature/sdk/testutils/FeatureProviderTestUtils.java
Fixes a bug that prevented the same provider from being registered with multiple names (or the same provider as default and with another name).
Note that I have not changed the behavior of `EventProvider.java` where it throws if multiple eventing attachments were attempted be to registered.
> fix: tolerate duplicate provider registrations

- src/main/java/dev/openfeature/sdk/exceptions/FlagNotFoundError.java
While working with OF, I noticed that in case a flag is not found, the whole stack trace is attached to the exception.
I think this info is not necessary for this type of exception since it is hidden from the end user, and the SDK only requires the `ErrorCode` field. 
I quickly configured some JMH tests that use the InMemory FlagD provider to test the performance gains in evaluating a flag that doesn't exist. The Score value represents the amount of FF evaluations done in a single millisecond. 
In a single thread case, the performance gain is >60%. 
```
"Benchmark","Mode","Threads","Samples","Score","Score Error (99,9%)","Unit"
"booleanNotFound_01Thread","thrpt",1,10,"459,324808","8,254488","ops/ms"
"booleanNotFound_02Thread","thrpt",2,10,"791,244898","8,644711","ops/ms" …
```
> perf: improve error handling

- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/sdk/ProviderRepository.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureAPITest.java
- src/test/java/dev/openfeature/sdk/ProviderRepositoryTest.java
- src/test/java/dev/openfeature/sdk/testutils/TestEventsProvider.java
As per [1.1.2.4](https://openfeature.dev/specification/sections/flag-evaluation#requirement-1124), the blocking provider setter must throw if init fails, so that application integrators can easily understand if their provider is working without attaching event handlers.
We implemented the wait functionality of this method, but we swallow the exception.
This PR fixes that.
> fix: setProviderAndWait must throw

- src/main/java/dev/openfeature/sdk/EvaluationContext.java
- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/main/java/dev/openfeature/sdk/Structure.java
- src/test/java/dev/openfeature/sdk/EvalContextTest.java
- src/test/java/dev/openfeature/sdk/ImmutableContextTest.java
Fixes #801. 
**What's changed?** 
I have changed how we store the targetingKey internally (in both mutable and immutable contexts). Instead of storing in a field, we now store targetingKey as a property of the delegated Structure implemementation. 
**Why** 
Both mutable and immutable contexts use a Structure implementation instance and delegate operations onto this instance. For example, `asObjectMap` and `asMap()` are exposed through this delegation. With this change, we keep the same delegation and expose targetingKey from the above-mentioned attribute exporters. 
**Impact**
There are no behaviour change other than for avoiding storing of empty string (`""`) for targetingKey.
> fix: improve targetingKey handling in the context

- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/test/java/dev/openfeature/sdk/ImmutableContextTest.java
- src/test/java/dev/openfeature/sdk/MutableContextTest.java
Problem:
getTargetingKey of missing targeting key causing NullPointerException.
Solution:
getTargetingKey of missing targeting key returns null.
failing _java-sdk-contrib_ [CI](https://github.com/open-feature/java-sdk-contrib/actions/runs/8314110946/job/22750876680?pr=722):
```
Error:  dev.openfeature.contrib.providers.flagd.resolver.process.targeting.OperatorTest.timestampPresent -- Time elapsed: 0.006 s <<< ERROR!
java.lang.NullPointerException
at dev.openfeature.sdk.ImmutableContext.getTargetingKey(ImmutableContext.java:65)
at dev.openfeature.contrib.providers.flagd.resolver.process.targeting.Operator.apply(Operator.java:52)
```
When adopting #805, saw an issue when [checking missing targeting](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/statsig/src/main/java/de …
> fix: missing targeting key should return null

- src/main/java/dev/openfeature/sdk/AbstractStructure.java
- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/test/java/dev/openfeature/sdk/ImmutableContextTest.java
- src/test/java/dev/openfeature/sdk/MutableContextTest.java
- first commit Added failing tests
- second commit Fixed the logic to allow the tests to pass by copying the passed in attributes
Fixes [#859](https://github.com/open-feature/java-sdk/issues/859)
> fix: issue #859

- README.md
- src/main/java/dev/openfeature/sdk/NoOpTransactionContextPropagator.java
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/ThreadLocalTransactionContextPropagator.java
- src/main/java/dev/openfeature/sdk/TransactionContextPropagator.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/sdk/LockingTest.java
- src/test/java/dev/openfeature/sdk/NoOpTransactionContextPropagatorTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureAPITest.java
- src/test/java/dev/openfeature/sdk/ThreadLocalTransactionContextPropagatorTest.java
- adds transactional context support
Fixes #819
- This is my first PR here, so I'll appreciate any feedback you can provide!
- I'm not sure if `OpenFeatureAPI` should use `NoOpTransactionContextPropagator` as a default `TransactionContextPropagator`, or if it can simply be `null`.
- I assume there was a mistake in the test `FlagEvaluationSpecTest.multi_layer_context_merges_correctly()` - attributes were put in the same `HashMap` twice. Have a look at it, please, and if I'm mistaken, I'll revert the changes.
> feat: context propagation

- src/main/java/dev/openfeature/sdk/EventSupport.java
is to ensure the shutdown method waits until the task executor (which is a daemon thread) has either completed shutdown or the timeout period elapses.
Fixes #683
I set the period to wait for completion to 3 seconds
n/a
n/a
> fix: shutdown method blocks until task executor shutdown completes

- src/main/java/dev/openfeature/sdk/Client.java
- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/sdk/MutableContextTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureAPITest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureClientTest.java
-Client Interface: Modified `setEvaluationContext` and `addHooks` to return `Client` instances, enabling chaining.
-MutableContext: Updated `setTargetingKey` to return a `MutableContext` instance.
-OpenFeatureAPI: Altered `setEvaluationContext` to return `OpenFeatureAPI` instances.
-OpenFeatureClient: Updated both `addHooks` and `setEvaluationContext` to return `OpenFeatureClient` instances.
-Added unit tests to verify chainability for each updated method.
Fixes: https://github.com/open-feature/java-sdk/issues/906
> fix: consistent method chainability

- src/main/java/dev/openfeature/sdk/EventDetails.java
- src/main/java/dev/openfeature/sdk/EventSupport.java
- src/main/java/dev/openfeature/sdk/FlagEvaluationDetails.java
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/sdk/ProviderEvaluation.java
- src/main/java/dev/openfeature/sdk/ProviderEventDetails.java
- src/main/java/dev/openfeature/sdk/ProviderRepository.java
removed all @javax.nullable annotations
Fixes #867
> fix: removed javax.nullable annotations

- pom.xml
- src/main/java/dev/openfeature/sdk/EventDetails.java
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
Was getting an unused local variable error due to "__" not being a named variable within try-with-resources blocks. Warnings have been suppressed.
https://stackoverflow.com/questions/16588843/why-does-try-with-resource-require-a-local-variable
#910
> fix: PMD warnings with new version

- README.md
- removes Go related snippet on the readme
- fixes example variable name on the readme
This addresses issues opened in the docs repo:
- https://github.com/open-feature/openfeature.dev/pull/574
- https://github.com/open-feature/openfeature.dev/pull/573
- https://github.com/open-feature/openfeature.dev/pull/582
> docs: remove golang snippet and fix variable name

- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
- src/test/java/dev/openfeature/sdk/DoSomethingProvider.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
This PR contains no functional changes, it:
- adds specific test for API context
- cleans up general merging test by using spy
- adds missing javadocs on API
fixes: https://github.com/open-feature/java-sdk/issues/939
:warning: Please don't merge before https://github.com/open-feature/java-sdk/pull/934 so we can avoid some conflicts.
> chore: javadoc and tests for api, context

- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/sdk/HookSpecTest.java
Fixes an issue where the fully merged and updated context was used in the evaluation, but not in all hooks.
Fixes: https://github.com/open-feature/java-sdk/issues/1047
> fix: updated context not passed to all hooks

- src/main/java/dev/openfeature/sdk/providers/memory/InMemoryProvider.java
- src/test/java/dev/openfeature/sdk/providers/memory/InMemoryProviderTest.java
- Use `ConcurrentHashMap` for `flags` in `InMemoryProvider` to make it thread-safe
Fixes #1054
> fix: Use ConcurrentHashMap for InMemoryProvider

- pom.xml
Workaround to make Mockito tests to pass under Java 21 due to this [open Mockito bug](https://github.com/mockito/mockito/issues/3121)
Fixes #1059
> fix: Pin byte-buddy(-agent) version to 1.14.19 to workaround Mockito issue

- src/main/java/dev/openfeature/sdk/BooleanHook.java
- src/main/java/dev/openfeature/sdk/DoubleHook.java
- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/IntegerHook.java
- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/StringHook.java
- src/main/java/dev/openfeature/sdk/internal/ExcludeFromGeneratedCoverageReport.java
Various small fixes to address warnings. None are functional.
> chore: various non-functional refactors

- README.md
- src/main/java/dev/openfeature/sdk/HookSupport.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/hooks/logging/LoggingHook.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
- src/test/java/dev/openfeature/sdk/hooks/logging/LoggingHookTest.java
Implements: https://github.com/open-feature/spec/pull/269
This PR removes logging from the main evaluation code path, with a couple exceptions: 
- unhandled errors in before/finally/error hooks (after hooks may throw in order to do validation)
- unhandled errors in event handlers
(IMO these represent bugs in code, since they should be handled, and not transient errors).
It also adds a `LoggingHook` as per the spec link above, which adds SLF4J structured logs for evaluation objects.
> feat: add logging hook, rm logging from evaluation

- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/exceptions/FlagNotFoundError.java
- src/main/java/dev/openfeature/sdk/exceptions/OpenFeatureErrorWithoutStacktrace.java
- src/main/java/dev/openfeature/sdk/exceptions/ProviderNotReadyError.java
- src/main/java/dev/openfeature/sdk/exceptions/TypeMismatchError.java
- src/test/java/dev/openfeature/sdk/AlwaysBrokenWithDetailsProvider.java
- src/test/java/dev/openfeature/sdk/FlagEvaluationSpecTest.java
So far, we used exceptions to handle our flow control, but Exceptions are costly. In the end, we enriched our
evaluation Details with errorCode and errorMessage. If desired, the providers can also handle this to reduce the execution footprint in erroneous cases, which don't have to be exceptions. Till now, we also converted those into exceptions and threw them, with this little code change, we would return already the details, and call the hooks, without exceptions being thrown.
For example, FlagNotFound is such a case; it can be expected and not exceptional. Hence, the exception flow might add too much overhead to performance-critical environments.
This implementation now allows the prover implementors to decide whether to support either or both.
Most likely this is something we also …
> feat: error resolution flow control without exceptions

- .mvn/wrapper/maven-wrapper.properties
- CONTRIBUTING.md
- mvnw
- mvnw.cmd
- adds Maven wrapper to the repository
mvn wrapper is also avialable in [java-sdk-contrib](https://github.com/open-feature/java-sdk-contrib/pull/811)
We may want to use mvnw in CI pipelines
run ./mvnw -version
> build: Add Maven wrapper

- CONTRIBUTING.md
- benchmark.txt
- pom.xml
- src/main/java/dev/openfeature/sdk/AbstractStructure.java
- src/main/java/dev/openfeature/sdk/HookSupport.java
- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/ImmutableStructure.java
- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/main/java/dev/openfeature/sdk/MutableStructure.java
- src/main/java/dev/openfeature/sdk/Structure.java
- src/main/java/dev/openfeature/sdk/internal/ObjectUtils.java
- src/test/java/dev/openfeature/sdk/benchmark/AllocationBenchmark.java
- src/test/java/dev/openfeature/sdk/benchmark/AllocationProfiler.java
- src/test/java/dev/openfeature/sdk/testutils/TestFlagsUtils.java
This PR reduces allocations of heap objects by ~70% for most use-cases. It does this by removing some usage of the streams API in some hotspots, and also being more efficient with `HashMaps` and context merging.
Benchmark results before/after these changes:
```
Benchmark                                         Mode  Cnt          Score   Error      Units
AllocationBenchmark.run                             ss               0.171               s/op
AllocationBenchmark.run:+totalAllocatedBytes        ss       440750800.000              bytes
AllocationBenchmark.run:+totalAllocatedInstances    ss        12086130.000          instances
AllocationBenchmark.run:+totalHeap                  ss       521412608.000  
```
```
Benchmark                                         Mode  Cnt          Score …
```
> perf: add heap benchmark and reduce allocations

- src/test/java/dev/openfeature/sdk/OpenFeatureClientTest.java
A test in this suite use the non-blocking provider set, which can result in flakiness in these cases since we aren't listening for a ready event.
> chore: flaky test

- CONTRIBUTING.md
- benchmark.txt
- src/main/java/dev/openfeature/sdk/AbstractStructure.java
- src/main/java/dev/openfeature/sdk/EvaluationContext.java
- src/main/java/dev/openfeature/sdk/ImmutableContext.java
- src/main/java/dev/openfeature/sdk/ImmutableStructure.java
- src/main/java/dev/openfeature/sdk/MutableContext.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/Structure.java
- src/main/java/dev/openfeature/sdk/Value.java
Continuation of https://github.com/open-feature/java-sdk/pull/1156; further reduces allocations, particularly of `ImmutableContext` and `HashMap`.
`HashMap` instances are reduced by more than 66%, memory usage decreased by another 40% in the benchmark.
Open `benchmark.txt` for results.
> perf: reduce hashmap allocations

- README.md
- src/main/java/dev/openfeature/sdk/Client.java
- src/main/java/dev/openfeature/sdk/FeatureProvider.java
- src/main/java/dev/openfeature/sdk/ImmutableTrackingEventDetails.java
- src/main/java/dev/openfeature/sdk/MutableTrackingEventDetails.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/main/java/dev/openfeature/sdk/Tracking.java
- src/main/java/dev/openfeature/sdk/TrackingEventDetails.java
- src/test/java/dev/openfeature/sdk/MutableTrackingEventDetailsTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureAPITest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureClientTest.java
- src/test/java/dev/openfeature/sdk/TrackingSpecTest.java
- adds support for Tracking as per Spec
Fixes #1164
> feat: implemented tracking as per spec

- README.md
- src/main/java/dev/openfeature/sdk/Hook.java
- src/main/java/dev/openfeature/sdk/HookSupport.java
- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/sdk/DeveloperExperienceTest.java
- src/test/java/dev/openfeature/sdk/HookSpecTest.java
- src/test/java/dev/openfeature/sdk/HookSupportTest.java
- src/test/java/dev/openfeature/sdk/OpenFeatureClientTest.java
Add flag evaluation details to finally hook stage 
- adds this new feature
Fixes #1246
> feat: Add evaluation details to finally hook stage #1246

- src/main/java/dev/openfeature/sdk/ImmutableMetadata.java
- src/test/java/dev/openfeature/sdk/FlagMetadataTest.java
- src/test/java/dev/openfeature/sdk/e2e/ContextStoringProvider.java
- src/test/java/dev/openfeature/sdk/e2e/State.java
- src/test/java/dev/openfeature/sdk/e2e/steps/ContextSteps.java
- src/test/java/dev/openfeature/sdk/e2e/steps/StepDefinitions.java
Implements the [recently added](https://github.com/open-feature/spec/pull/293) gherkin tests 
Part of https://github.com/open-feature/flagd-testbed/issues/13
> feat: implement gherkin tests

- src/main/java/dev/openfeature/sdk/OpenFeatureClient.java
- src/test/java/dev/openfeature/sdk/FatalErrorProvider.java
- src/test/java/dev/openfeature/sdk/HookSpecTest.java
Fixes a bug where our "short circuit" logic was "short circuiting" too early, leading to various errors in hooks.
Fixes: https://github.com/open-feature/java-sdk/issues/1370
> fix: hooks not run in NOT_READY/FATAL

- README.md
- src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java
**Fixes #1424**
This PR improves the README examples by wrapping the setProviderAndWait method inside a try-catch block.
Since setProviderAndWait can throw an exception if the provider initialization fails, it's important to handle it safely to prevent unexpected crashes during runtime.
**Changes made:**
- Updated the main usage example to wrap setProviderAndWait with a try-catch.
- Updated the synchronous usage section with a try-catch block and explanatory comment.
**Why?**
- Improves the reliability and production-readiness of the documentation examples.
- Helps users adopt better error handling practices from the start.
**Checklist:**
> docs: add try-catch example for setProviderAndWait usage

- .github/workflows/release.yml
A few improvements to our release workflow:
- splits release into 2 jobs, this is nice because we can re-run the actual maven publish independently if it fails due to an issue with OSSRH
- skips tests on maven publish (no point in testing again when we are publishing)
> chore: improvements to release workflow

- pom.xml
- src/test/java/dev/openfeature/sdk/e2e/steps/ProviderSteps.java
- src/test/java/dev/openfeature/sdk/vmlens/VmLensCT.java
Renamed the VmLensTest to VmLensCT and changed the VMLens plugin config to include only tests with postfix CT.
Fixes #1611
The VMLens test no takes something around 4s.
Please let me know if you prefer a special profile, or if the time is now o.k.
> fix: improve vmlens handling
